name: lint
on:
  push:
  pull_request:

jobs:
  lint:
    uses: charmbracelet/meta/.github/workflows/lint.yml@main
    permissions:
      contents: read
      checks: write
      pull-requests: read
    with:
      golangci_path: .golangci.yml
